/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConveniosRouteImport } from './routes/convenios'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransacoesIndexRouteImport } from './routes/transacoes.index'
import { Route as TransacoesNovaRouteImport } from './routes/transacoes.nova'
import { Route as TransacoesIdRouteImport } from './routes/transacoes.$id'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConveniosRoute = ConveniosRouteImport.update({
  id: '/convenios',
  path: '/convenios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesIndexRoute = TransacoesIndexRouteImport.update({
  id: '/transacoes/',
  path: '/transacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesNovaRoute = TransacoesNovaRouteImport.update({
  id: '/transacoes/nova',
  path: '/transacoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesIdRoute = TransacoesIdRouteImport.update({
  id: '/transacoes/$id',
  path: '/transacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contas': typeof ContasRoute
  '/convenios': typeof ConveniosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/transacoes/$id': typeof TransacoesIdRoute
  '/transacoes/nova': typeof TransacoesNovaRoute
  '/transacoes/': typeof TransacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contas': typeof ContasRoute
  '/convenios': typeof ConveniosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/transacoes/$id': typeof TransacoesIdRoute
  '/transacoes/nova': typeof TransacoesNovaRoute
  '/transacoes': typeof TransacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contas': typeof ContasRoute
  '/convenios': typeof ConveniosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/transacoes/$id': typeof TransacoesIdRoute
  '/transacoes/nova': typeof TransacoesNovaRoute
  '/transacoes/': typeof TransacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contas'
    | '/convenios'
    | '/login'
    | '/perfil'
    | '/transacoes/$id'
    | '/transacoes/nova'
    | '/transacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contas'
    | '/convenios'
    | '/login'
    | '/perfil'
    | '/transacoes/$id'
    | '/transacoes/nova'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/contas'
    | '/convenios'
    | '/login'
    | '/perfil'
    | '/transacoes/$id'
    | '/transacoes/nova'
    | '/transacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContasRoute: typeof ContasRoute
  ConveniosRoute: typeof ConveniosRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  TransacoesIdRoute: typeof TransacoesIdRoute
  TransacoesNovaRoute: typeof TransacoesNovaRoute
  TransacoesIndexRoute: typeof TransacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convenios': {
      id: '/convenios'
      path: '/convenios'
      fullPath: '/convenios'
      preLoaderRoute: typeof ConveniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes/': {
      id: '/transacoes/'
      path: '/transacoes'
      fullPath: '/transacoes/'
      preLoaderRoute: typeof TransacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes/nova': {
      id: '/transacoes/nova'
      path: '/transacoes/nova'
      fullPath: '/transacoes/nova'
      preLoaderRoute: typeof TransacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes/$id': {
      id: '/transacoes/$id'
      path: '/transacoes/$id'
      fullPath: '/transacoes/$id'
      preLoaderRoute: typeof TransacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContasRoute: ContasRoute,
  ConveniosRoute: ConveniosRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  TransacoesIdRoute: TransacoesIdRoute,
  TransacoesNovaRoute: TransacoesNovaRoute,
  TransacoesIndexRoute: TransacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
